backend:
  name: git-gateway
  branch: main

media_folder: '/static/media'
public_folder: '/media'

collections:
  - name: 'designers'
    media_folder: ''
    public_folder: ''
    label: 'Designers'
    folder: 'content/designers'
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'title', widget: 'string'}
      - {label: "Course", name: "course", widget: "select", options: ["Graphic Design", "UX/UI Design"]}
      - { label: 'Introduction', name: 'introduction', widget: 'string' }
      - { label: 'Profile Image', name: 'thumbnail', widget: 'image'}
      - label: "Portfolio & Social media links"
        hint: "Seperate each item with a comma. Use full URL: include https://..."
        name: "links"
        widget: "list"
        default: [""]
      - label: "Projects"
        name: "projects"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Video", name: "video", widget: "string", hint: 'Must be Vimeo or YouTube URL', required: false }
          - label: "Images (MUST BE BELOW 750KB)"
            hint: "All images must be below 750kb and either PNGs or JPEGs"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "src", widget: "image"}