backend:
  name: git-gateway
  branch: main

media_folder: '/static/media'
public_folder: '/media'

collections:
  - name: 'designers'
    media_folder: ''
    public_folder: ''
    label: 'Designers'
    folder: 'content/designers'
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string'}
      - { label: 'Introduction', name: 'introduction', widget: 'markdown' }
      - { label: 'Cover Image', name: 'thumbnail', widget: 'image'}
      - { label: 'Color', name: 'color', widget: 'color', required: false}
      - label: "Links"
        name: "links"
        widget: "list"
        default: [""]
      - label: "Projects"
        name: "project"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "string", required: false }
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "src", widget: "image" }